FROM node:20
USER root
WORKDIR /home/node/app
COPY backend/package.json backend/pnpm-lock.yaml ./
COPY backend/tsconfig.json .
COPY backend/src ./src
RUN npm install -g pnpm
RUN pnpm --prefix ./backend install
RUN pnpm tsx ./backend/src/swagger.ts
ENV PORT=3000
ENV DATABASE_URL=mongodb://root:mongo2023@localhost:27017
EXPOSE 3000
CMD [ "pnpm", "start"]