apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: 
    app: backend
spec:
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-tech-challange
        image: dcleme17/fiap-tc-backend:fase2
        imagePullPolicy: Always        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000     
        livenessProbe: 
          httpGet:
            path: /api/health-check/v1
            port: 3000
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20 
        readinessProbe:
          httpGet:
            path: /api/health-check/v1
            port: 3000
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 3                    
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: backend
                key: PORT
          - name: MERCADOPAGO_URL
            valueFrom:
              configMapKeyRef:
                name: backend
                key: MERCADOPAGO_URL
          - name: MERCADOPAGO_WEBHOOK_URL
            valueFrom:
              configMapKeyRef:
                name: backend
                key: MERCADOPAGO_WEBHOOK_URL
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: backend
                key: DATABASE_URL  
          - name: MERCADOPAGO_USERID
            valueFrom:
              secretKeyRef:
                name: backend
                key: MERCADOPAGO_USERID  
          - name: MERCADOPAGO_TOKEN
            valueFrom:
              secretKeyRef:
                name: backend
                key: MERCADOPAGO_TOKEN  
          - name: MERCADOPAGO_POS
            valueFrom:
              secretKeyRef:
                name: backend
                key: MERCADOPAGO_POS  
  replicas: 2
  selector:
    matchLabels:
      app: backend