apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYjovL3Jvb3Q6ZmlhcGdydXBvMjJAZGF0YWJhc2U6ODA=
  MERCADOPAGO_USERID: ODQ5Njc2MzI=
  MERCADOPAGO_TOKEN: VEVTVC0yNDA3NDIwNTk0MDM5MjUxLTAzMDIyMi1iZWM5NTM5YTZiYTVjYWU3MjBiNGY2ZDA3YWQzYmQ3YS04NDk2NzYzMg==
  MERCADOPAGO_POS: U1VDMDAx