apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  
  resources:
    requests:
      storage: 3Mi