apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /Users/daniel.clemente/fiap-tech-challenge-grupo22/data/db
