apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels: 
    app: mongo-express
spec:
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
            value: "true"
          - name: ME_CONFIG_BASICAUTH_USERNAME 
            value: fiap
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            value: fiap2023
          - name: ME_CONFIG_MONGODB_PORT
            value: "80"
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: root
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: fiapgrupo22   
          - name: ME_CONFIG_MONGODB_URL
            value: mongodb://root:fiapgrupo22@database:80
       
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"           
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
